site_name: Vapor Docs
copyright: 'Copyright &copy; 2019 Qutheory, LLC'
site_url: 'https://docs.vapor.codes/4.0/'
repo_url: http://github.com/vapor/vapor
edit_uri: https://github.com/vapor/documentation/edit/master/4.0/docs/
theme:
  name: 'material'
  palette:
    primary: 'black'
    accent: 'blue'
  logo: 'logo.png'
extra:
  social:
    - type: 'twitter'
      link: 'https://twitter.com/@codevapor'
    - type: 'slack'
      link: 'http://vapor.team/'
    - type: 'github'
      link: 'https://github.com/vapor'
  font:
    text: 'Roboto Slab'
    code: 'Source Code Pro'
  # disqus: 'vapor-docs'
google_analytics:
  - 'UA-76177358-4'
  - 'auto'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
nav:
- 'Welcome': 'index.md'
- 'Install':
  - 'macOS': 'install/macos.md'
  - 'Ubuntu': 'install/ubuntu.md'